AWSTemplateFormatVersion: 2010-09-09

Resources:
  S3AccessPolicyWithAnotherAccount:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3AccessPolicyInAnotherAccount
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 
              - sts:AssumeRole
            Resource: arn:aws:iam::055839481846:role/CrossAccountRoleForCrossAccoutUser
      Users:
        - developer
