AWSTemplateFormatVersion: 2010-09-09

Resources:
  S3AccessPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: DeveloperUserS3AccessPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:GetBucketLocation
              - s3:ListBucket
            Resource: arn:aws:s3:::isheejong-production-app
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
            Resource: "*"