AWSTemplateFormatVersion: 2010-09-09

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't2.micro'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: 'ssmdemossh'
      ImageId: 'ami-0704a255aaf5a4f73'
  
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't2.micro'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: 'ssmdemossh'
      ImageId: 'ami-0704a255aaf5a4f73'
      
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't2.micro'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: 'ssmdemossh'
      ImageId: 'ami-0704a255aaf5a4f73'
      
  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't2.micro'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: 'ssmdemossh'
      ImageId: 'ami-0704a255aaf5a4f73'

  EC2Instance4:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't2.micro'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: 'ssmdemossh'
      ImageId: 'ami-0704a255aaf5a4f73'
      
  EC2Instance5:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't2.micro'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: 'ssmdemossh'
      ImageId: 'ami-0704a255aaf5a4f73'
      
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'